name: ATT-AttentiveFP-CI
channels:
  - rdkit
  - pytorch
  - dglteam
  - defaults
dependencies:
  - ipython=7.26.0
  - matplotlib-base=3.4.3
  - matplotlib=3.4.3
  - molvs=0.1.1
  - numpy=1.21.2
  - pandas=1.3.0
  - pip=21.0.1
  - pytorch=1.12.1
  - scikit-learn=0.24.2
  - scipy=1.6.2
  - tqdm=4.62.1
  - requests=2.26.0
  - jupyter
